### **Итоговое задание Альмиры, Андрея Скороходова и Соколова Александра**  
### по Проекту 6. Car Price prediction 
####  Юнит 6. Основные алгоритмы машинного обучения. Часть II (отредактирован 09.09.2020)
---
## Часть 1. Парсинг
### 1. Импорт библиотек

In [1]:
import pandas as pd
import requests, json
import time
import os

import os

pd.options.mode.chained_assignment = None

# этот блок закомментирован так как используется только на kaggle
"""
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
PATH_to_file = '/kaggle/input/sf-dst-car-price/'
PATH_to_file_data = '/kaggle/input/all-brands-and-models-for-auto-ru-09-09-2020/'
"""

# # # этот блок закомментирован так как используется только локальной машине
from importlib import reload
print(os.listdir('./data/'))
PATH_to_file = './data/'

['.~lock.test.csv#', 'sample_submission.csv', 'test.csv']

In [285]:
#df_t = pd.read_csv(PATH_to_file + 'autoru-19.csv', index_col=0)
df_t = pd.read_csv(r'C:\Users\ivans\Downloads\autoru-23.csv', index_col=0)
df_t2 = pd.read_csv(r'C:\Users\ivans\Downloads\autoru2499.csv', index_col=0)
df_t3 = pd.read_csv(r'C:\Users\ivans\Downloads\autoru5699.csv', index_col=0)
df_t = pd.concat([df_t, df_t2, df_t3])
df_t = df_t.drop_duplicates(subset=['id'])

In [2]:
df_nnn = pd.read_csv(r'train.csv')

In [4]:
train = df_nnn.copy()

In [5]:
train

,bodyType,brand,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,mileage,...,super_gen,vehicleConfiguration,vehicleTransmission,vendor,Владельцы,ПТС,Привод,Руль,id,price
0,Седан,AUDI,синий,{'id': '0'},- Комплектация:\t2.0 190 л.с.\n- Климат-контро...,2.0 LTR,190 N12,"{'engine-proof': True, 'asr': True, 'start-sto...",бензин,92395,...,"{'id': '20637733', 'displacement': 1984, 'engi...",SEDAN ROBOT 2.0,ROBOT,EUROPEAN,2.0,ORIGINAL,передний,LEFT,1102840467,1792000
1,Седан,AUDI,белый,"{'id': '6937691', 'name': 'Базовая', 'availabl...",ВЫГОДА ПРИ ПОКУПКЕ В КРЕДИТ ОТ 20 000 ДО 100 0...,2.0 LTR,180 N12,"{'cruise-control': True, 'asr': True, 'tinted-...",бензин,119054,...,"{'id': '7345621', 'displacement': 1984, 'engin...",SEDAN VARIATOR 2.0,VARIATOR,EUROPEAN,4.0,DUPLICATE,передний,LEFT,1101747921,1165000
2,Седан,AUDI,серый,{'id': '0'},ЛОТ: 01249598\nFAVORIT MOTORS KIA МКАД\n\nВы м...,1.8 LTR,160 N12,"{'asr': True, 'esp': True, 'airbag-driver': Tr...",бензин,182260,...,"{'id': '2324133', 'displacement': 1798, 'engin...",SEDAN VARIATOR 1.8,VARIATOR,EUROPEAN,4.0,ORIGINAL,передний,LEFT,1102811839,755000
3,Внедорожник 5 дв.,AUDI,оранжевый,"{'id': '20259940', 'name': 'Базовая', 'availab...","Все автомобили, представленные в продаже, прох...",2.0 LTR,177 N12,"{'cruise-control': True, 'tinted-glass': True,...",дизель,98000,...,"{'id': '7857338', 'displacement': 1968, 'engin...",ALLROAD_5_DOORS ROBOT 2.0,ROBOT,EUROPEAN,1.0,ORIGINAL,полный,LEFT,1102465243,1115000
4,Седан,AUDI,чёрный,"{'id': '21793195', 'name': 'Advance 40 TFSI S ...",Комплектация: Audi A6 Advance 40 TFSI S tronic...,40 LTR,190 N12,"{'cruise-control': True, 'asr': True, 'esp': T...",бензин,0,...,"{'id': '21791690', 'nameplate': '40 TFSI', 'di...",SEDAN ROBOT 40,ROBOT,EUROPEAN,NaN,ORIGINAL,передний,LEFT,1102898624,3690000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167393,Внедорожник 5 дв.,MERCEDES,серый,"{'id': '21565471', 'name': 'GLC 300 4MATIC Spo...",Эксклюзивные условия в «Звезда Столицы Каширка...,300 LTR,249 N12,"{'218': True, '234': True, '345': True, '440':...",бензин,0,...,"{'id': '21692541', 'name': '300', 'nameplate':...",ALLROAD_5_DOORS AUTOMATIC 300,AUTOMATIC,EUROPEAN,NaN,ORIGINAL,полный,LEFT,1102983990,5512000
167394,Седан,MERCEDES,чёрный,"{'id': '22474298', 'name': 'E 200 4MATIC Sport...",Панавто – официальный дилер «Мерседес-Бенц».\n...,200 LTR,197 N12,"{'cruise-control': True, 'asr': True, 'esp': T...",бензин,0,...,"{'id': '22296545', 'name': '200', 'nameplate':...",SEDAN AUTOMATIC 200,AUTOMATIC,EUROPEAN,NaN,ORIGINAL,полный,LEFT,1102639353,4312000
167395,Седан,MERCEDES,чёрный,"{'id': '22474298', 'name': 'E 200 4MATIC Sport...",Эксклюзивные условия в «Звезда Столицы Каширка...,200 LTR,197 N12,"{'218': True, '500': True, '632': True, '873':...",бензин,0,...,"{'id': '22296545', 'name': '200', 'nameplate':...",SEDAN AUTOMATIC 200,AUTOMATIC,EUROPEAN,NaN,ORIGINAL,полный,LEFT,1102983920,4900000
167396,Внедорожник 5 дв.,MERCEDES,чёрный,"{'id': '21217612', 'name': 'AMG G 63', 'availa...",Установлено дополнительное оборудование дилера...,63 LTR,585 N12,"{'sport-seats': True, 'e-adjustment-wheel': Tr...",бензин,0,...,"{'id': '21203530', 'name': '63 AMG', 'nameplat...",ALLROAD_5_DOORS AUTOMATIC 63,AUTOMATIC,EUROPEAN,NaN,ORIGINAL,полный,LEFT,1102368788,19462000
167397,Внедорожник 5 дв.,MERCEDES,красный,"{'id': '21829752', 'name': 'GLE 350 d 4MATIC',...",Установлено дополнительное оборудование дилера...,350 LTR,249 N12,"{'cruise-control': True, 'asr': True, 'tinted-...",дизель,0,...,"{'id': '21829696', 'name': '350', 'nameplate':...",ALLROAD_5_DOORS AUTOMATIC 350,AUTOMATIC,EUROPEAN,NaN,ORIGINAL,полный,LEFT,1102225125,8525200

In [471]:
df_tnew = pd.DataFrame()

df_tnew['bodyType'] = ''
df_tnew['brand'] = ''
df_tnew['color'] = df_t['color_hex']
df_tnew['complectation_dict'] = ''
df_tnew['description'] = df_t['description']
df_tnew['engineDisplacement'] = ''
df_tnew['enginePower'] = ''
df_tnew['equipment_dict'] = ''
df_tnew['fuelType'] = ''
df_tnew['mileage'] = ''
df_tnew['modelDate'] = ''
df_tnew['model_info'] = ''
df_tnew['model_name'] = ''
df_tnew['name'] = ''
df_tnew['numberOfDoors'] = ''
df_tnew['priceCurrency'] = 'RUB'
df_tnew['productionDate'] = ''
df_tnew['sell_id'] = df_t['saleId']
df_tnew['super_gen'] = ''
df_tnew['vehicleConfiguration'] = ''
df_tnew['vehicleTransmission'] = ''
df_tnew['vendor'] = ''
df_tnew['Владельцы'] = ''
df_tnew['ПТС'] = ''
df_tnew['Привод'] = ''
df_tnew['Руль'] = ''
df_tnew['id'] = df_t['id']
df_tnew['price'] = ''

In [479]:
def first_level(df, new_df, column, parametr, new_parametr):
    iterator = 0
    for x in df[column]:
        if x is not None:
            try:
                new_df[new_parametr][iterator] = eval(x)[parametr]
            except:
                new_df[new_parametr][iterator] = ''
        iterator += 1
        
def second_level(df, new_df, column, parametr_1, parametr_2, new_parametr):
    iterator = 0
    for x in df[column]:
        if x is not None:
            try:
                new_df[new_parametr][iterator] = eval(x)[parametr_1][parametr_2]
            except:
                new_df[new_parametr][iterator] = ''
        iterator += 1

In [475]:
first_level(df_t, df_tnew, 'vehicle_info', 'complectation', 'complectation_dict')
first_level(df_t, df_tnew, 'vehicle_info', 'equipment', 'equipment_dict')
first_level(df_t, df_tnew, 'state', 'mileage', 'mileage')
first_level(df_t, df_tnew, 'vehicle_info', 'model_info', 'model_info')
first_level(df_t, df_tnew, 'documents', 'year', 'productionDate')
first_level(df_t, df_tnew, 'vehicle_info', 'tech_param', 'super_gen')
first_level(df_t, df_tnew, 'vehicle_info', 'vendor', 'vendor')
first_level(df_t, df_tnew, 'documents', 'owners_number', 'Владельцы')
first_level(df_t, df_tnew, 'documents', 'pts', 'ПТС')
first_level(df_t, df_tnew, 'vehicle_info', 'steering_wheel', 'Руль')
first_level(df_t, df_tnew, 'price_info', 'price', 'price')
second_level(df_t, df_tnew, 'vehicle_info', 'configuration', 'human_name', 'bodyType')
second_level(df_t, df_tnew, 'vehicle_info', 'mark_info', 'code', 'brand')
second_level(df_t, df_tnew, 'vehicle_info', 'tech_param', 'human_name', 'engineDisplacement')
second_level(df_t, df_tnew, 'vehicle_info', 'tech_param', 'power', 'enginePower')
second_level(df_t, df_tnew, 'vehicle_info', 'super_gen', 'year_from', 'modelDate')
second_level(df_t, df_tnew, 'vehicle_info', 'model_info', 'code', 'model_name')
second_level(df_t, df_tnew, 'vehicle_info', 'tech_param', 'human_name', 'name')
second_level(df_t, df_tnew, 'vehicle_info', 'configuration', 'doors_count', 'numberOfDoors')
second_level(df_t, df_tnew, 'vehicle_info', 'tech_param', 'transmission', 'vehicleTransmission')

NameError: name 'new_parametr_1' is not defined

In [486]:
# парочка ручных обработок для нетипичных случаев

iterator = 0
for x in df_t['lk_summary']:
    if x is not None:        
        try:
            df_tnew['fuelType'][iterator] = x.split(' ')[-1]
        except:
            df_tnew['fuelType'][iterator] = ''
    iterator += 1
    
iterator = 0
for x in df_t['lk_summary']:
    if x is not None:        
        try:
            df_tnew['Привод'][iterator] = x.split(' ')[-2][:-1]
        except:
            df_tnew['Привод'][iterator] = ''
    iterator += 1

iterator = 0
for x in df_tnew['engineDisplacement']:    
    df_tnew['engineDisplacement'][iterator] = str(x[:3]) + ' LTR'
    iterator += 1
    
iterator = 0
for x in df_tnew['enginePower']:
    df_tnew['enginePower'][iterator] = str(x) + ' N12'
    iterator += 1

iterator = 0
for x in df_tnew['sell_id']:
    df_tnew['sell_id'][iterator] = str(x[:10])
    iterator += 1
    
iterator = 0
for x in df_t['vehicle_info']:
    if x is not None:
        try:
            df_tnew['vehicleConfiguration'][iterator] = \
            eval(x)['configuration']['body_type'] + ' ' + \
            eval(x)['tech_param']['transmission'] + ' ' + \
            eval(x)['tech_param']['human_name'][:3]
        except:
            df_tnew['vehicleConfiguration'][iterator] = ''
    iterator += 1

In [498]:
# исправляем название цветов
color_dict = {'040001' : 'чёрный', 'FAFBFB' : 'белый', '97948F' : 'серый', 'CACECB' : 'серебристый', '0000CC' : 'синий', 'EE1D19' : 'красный', \
              '200204' : 'коричневый', '007F00' : 'зелёный', 'C49648' : 'бежевый', '22A0F8' : 'голубой', 'DEA522' : 'золотистый', '660099' : 'пурпурный', \
              'FF8649' : 'оранжевый', '4A2197' : 'фиолетовый', 'FFD600' : 'жёлтый', 'FFC0CB' : 'розовый'}

iterator = 0
for x in df_tnew['color']:
    df_tnew['color'][iterator] = color_dict[x]    
    iterator += 1

In [501]:
df_tnew

,bodyType,brand,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,mileage,...,super_gen,vehicleConfiguration,vehicleTransmission,vendor,Владельцы,ПТС,Привод,Руль,id,price
availability,,,,,,,,,,,,,,,,,,,,,
IN_STOCK,Седан,AUDI,синий,{'id': '0'},- Комплектация:\t2.0 190 л.с.\n- Климат-контро...,2.0 LTR,190 N12,"{'engine-proof': True, 'asr': True, 'start-sto...",бензин,92395,...,"{'id': '20637733', 'displacement': 1984, 'engi...",SEDAN ROBOT 2.0,ROBOT,EUROPEAN,2,ORIGINAL,передний,LEFT,1102840467,1792000
IN_STOCK,Седан,AUDI,белый,"{'id': '6937691', 'name': 'Базовая', 'availabl...",ВЫГОДА ПРИ ПОКУПКЕ В КРЕДИТ ОТ 20 000 ДО 100 0...,2.0 LTR,180 N12,"{'cruise-control': True, 'asr': True, 'tinted-...",бензин,119054,...,"{'id': '7345621', 'displacement': 1984, 'engin...",SEDAN VARIATOR 2.0,VARIATOR,EUROPEAN,4,DUPLICATE,передний,LEFT,1101747921,1165000
IN_STOCK,Седан,AUDI,серый,{'id': '0'},ЛОТ: 01249598\nFAVORIT MOTORS KIA МКАД\n\nВы м...,1.8 LTR,160 N12,"{'asr': True, 'esp': True, 'airbag-driver': Tr...",бензин,182260,...,"{'id': '2324133', 'displacement': 1798, 'engin...",SEDAN VARIATOR 1.8,VARIATOR,EUROPEAN,4,ORIGINAL,передний,LEFT,1102811839,755000
IN_STOCK,Внедорожник 5 дв.,AUDI,оранжевый,"{'id': '20259940', 'name': 'Базовая', 'availab...","Все автомобили, представленные в продаже, прох...",2.0 LTR,177 N12,"{'cruise-control': True, 'tinted-glass': True,...",дизель,98000,...,"{'id': '7857338', 'displacement': 1968, 'engin...",ALLROAD_5_DOORS ROBOT 2.0,ROBOT,EUROPEAN,1,ORIGINAL,полный,LEFT,1102465243,1115000
IN_STOCK,Седан,AUDI,чёрный,"{'id': '21793195', 'name': 'Advance 40 TFSI S ...",Комплектация: Audi A6 Advance 40 TFSI S tronic...,40 LTR,190 N12,"{'cruise-control': True, 'asr': True, 'esp': T...",бензин,0,...,"{'id': '21791690', 'nameplate': '40 TFSI', 'di...",SEDAN ROBOT 40,ROBOT,EUROPEAN,,ORIGINAL,передний,LEFT,1102898624,3690000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IN_STOCK,Внедорожник 5 дв.,MERCEDES,серый,"{'id': '21565471', 'name': 'GLC 300 4MATIC Spo...",Эксклюзивные условия в «Звезда Столицы Каширка...,300 LTR,249 N12,"{'218': True, '234': True, '345': True, '440':...",бензин,0,...,"{'id': '21692541', 'name': '300', 'nameplate':...",ALLROAD_5_DOORS AUTOMATIC 300,AUTOMATIC,EUROPEAN,,ORIGINAL,полный,LEFT,1102983990,5512000
IN_STOCK,Седан,MERCEDES,чёрный,"{'id': '22474298', 'name': 'E 200 4MATIC Sport...",Панавто – официальный дилер «Мерседес-Бенц».\n...,200 LTR,197 N12,"{'cruise-control': True, 'asr': True, 'esp': T...",бензин,0,...,"{'id': '22296545', 'name': '200', 'nameplate':...",SEDAN AUTOMATIC 200,AUTOMATIC,EUROPEAN,,ORIGINAL,полный,LEFT,1102639353,4312000
IN_STOCK,Седан,MERCEDES,чёрный,"{'id': '22474298', 'name': 'E 200 4MATIC Sport...",Эксклюзивные условия в «Звезда Столицы Каширка...,200 LTR,197 N12,"{'218': True, '500': True, '632': True, '873':...",бензин,0,...,"{'id': '22296545', 'name': '200', 'nameplate':...",SEDAN AUTOMATIC 200,AUTOMATIC,EUROPEAN,,ORIGINAL,полный,LEFT,1102983920,4900000
IN_STOCK,Внедорожник 5 дв.,MERCEDES,чёрный,"{'id': '21217612', 'name': 'AMG G 63', 'availa...",Установлено дополнительное оборудование дилера...,63 LTR,585 N12,"{'sport-seats': True, 'e-adjustment-wheel': Tr...",бензин,0,...,"{'id': '21203530', 'name': '63 AMG', 'nameplat...",ALLROAD_5_DOORS AUTOMATIC 63,AUTOMATIC,EUROPEAN,,ORIGINAL,полный,LEFT,1102368788,19462000
IN_STOCK,Внедорожник 5 дв.,MERCEDES,красный,"{'id': '21829752', 'name': 'GLE 350 d 4MATIC',...",Установлено дополнительное оборудование дилера...,350 LTR,249 N12,"{'cruise-control': True, 'asr': True, 'tinted-...",дизель,0,...,"{'id': '21829696', 'name': '350', 'nameplate':...",ALLROAD_5_DOORS AUTOMATIC 350,AUTOMATIC,EUROPEAN,,ORIGINAL,полный,LEFT,1102225125,8525200

In [10]:
df_nnn.to_csv('train.csv', index = False)

In [281]:
second_level(df_t, df_tnew, 'vehicle_info', 'configuration', 'doors_count', 'numberOfDoors')

In [274]:
first_level(df_t, df_tnew, 'discount_price', 'price', 'discount_price')

In [282]:
df_tnew['numberOfDoors'].value_counts()

5    17538
4     7288
3      814
2      406
Name: numberOfDoors, dtype: int64

In [278]:
df_t['auto_class']

KeyError: 'auto_class'

In [269]:
eval(df_t['vehicle_info'][0])['configuration']

{'id': '20637561',
 'body_type': 'SEDAN',
 'doors_count': 4,
 'auto_class': 'D',
 'human_name': 'Седан',
 'trunk_volume_min': 480,
 'body_type_group': 'SEDAN',
 'main_photo': {'sizes': {'orig': '//avatars.mds.yandex.net/get-verba/787013/2a0000016090358a3513690850fcf485d70a/orig',
   'wizardv3mr': '//avatars.mds.yandex.net/get-verba/787013/2a0000016090358a3513690850fcf485d70a/wizardv3mr',
   'cattouch': '//avatars.mds.yandex.net/get-verba/787013/2a0000016090358a3513690850fcf485d70a/cattouch'}},
 'tags': ['liquid', 'medium', 'fivestars']}

In [113]:
df_t.drop(columns=['category','delivery_info','discount_options','is_favorite','old_category_id',\
                   'score','services','shark_info','status','counters','grouping_info','hash','price_history',\
                   'recall_info','salon','seller','service_prices','sub_category','multiposting','dealer_credit_config',\
                   'brand_cert_info','badges'])

,description,documents,owner_expenses,section,seller_type,tags,additional_info,id,price_info,relevance,saleId,state,vehicle_info,lk_summary,discount_price
availability,,,,,,,,,,,,,,,
IN_STOCK,ВЛАДЕЛЕЦ ОДИН! Первая запись автосалон( хотели...,"{'owners_number': 1, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 18675, 'year...",used,PRIVATE,"['proven_owner', 'oversize', 'vin_resolution_u...","{'hidden': False, 'is_on_moderation': False, '...",1102956027,"{'price': 3500000, 'currency': 'RUR', 'EUR': 3...",{'catboost_relevance_offline': 0.0035856235194...,1102956027-d5dbb784,"{'mileage': 41000, 'state_not_beaten': True, '...","{'configuration': {'id': '20849260', 'body_typ...","2.0 AMT (249 л.с.), внедорожник, полный, бензин",NaN
IN_STOCK,Куплен в салоне АЦ Космонавтов в октябре 2020....,"{'owners_number': 1, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 1410, 'year'...",used,PRIVATE,"['proven_owner', 'compact', 'medium', 'prestig...","{'hidden': False, 'is_on_moderation': False, '...",1102853255,"{'price': 1940000, 'currency': 'RUR', 'EUR': 2...",{'catboost_relevance_offline': 0.2673173747505...,1102853255-0c76c5f1,"{'damages': [{'car_part': 'FRONT_LEFT_FENDER',...","{'configuration': {'id': '20785541', 'body_typ...","1.4 AMT (150 л.с.), седан, передний, бензин",NaN
IN_STOCK,"Абсолютно исправный и обслуженный автомобиль,б...","{'owners_number': 3, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 18375, 'year...",used,PRIVATE,"['big', 'oversize', 'vin_service_history', 'pr...","{'hidden': False, 'is_on_moderation': False, '...",1103039750,"{'price': 1900000, 'currency': 'RUR', 'EUR': 2...",{'catboost_relevance_offline': 0.0035755663492...,1103039750-c0f1075d,"{'mileage': 164000, 'state_not_beaten': True, ...","{'configuration': {'id': '6468932', 'body_type...","3.0d AT (245 л.с.), внедорожник, полный, дизель",NaN
IN_STOCK,При покупке данного автомобиля в кредит вы пол...,"{'owners_number': 1, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 16875, 'year...",used,COMMERCIAL,"['oversize', 'medium', 'fivestars', 'prestige'...","{'hidden': False, 'is_on_moderation': False, '...",1102024733,"{'price': 1415000, 'currency': 'RUR', 'EUR': 1...",{'catboost_relevance_offline': 0.4052365388992...,1102024733-a6c46c7a,"{'mileage': 99000, 'state_not_beaten': True, '...","{'configuration': {'id': '8351305', 'body_type...","2.0 AT (225 л.с.), внедорожник, полный, бензин",NaN
IN_STOCK,"Все автомобили, представленные в продаже, прох...","{'owners_number': 4, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 9500, 'year'...",used,COMMERCIAL,"['big', 'medium', 'prestige', 'allowed_for_cre...","{'hidden': False, 'is_on_moderation': False, '...",1101402687,"{'price': 1265000, 'currency': 'RUR', 'EUR': 1...",{'catboost_relevance_offline': 0.3054480143450...,1101402687-068c2b33,"{'mileage': 77000, 'state_not_beaten': True, '...","{'configuration': {'id': '20246013', 'body_typ...","1.8 AMT (190 л.с.), седан, передний, бензин",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IN_STOCK,Реальный пробег. Без окрасов.\nБолее 150 автом...,"{'owners_number': 2, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 5215, 'year'...",used,COMMERCIAL,"['oversize', 'allowed_for_credit', 'big-trunk'...","{'hidden': False, 'is_on_moderation': False, '...",1103134661,"{'price': 835000, 'currency': 'RUR', 'EUR': 90...",{'catboost_relevance_offline': 0.0033161213768...,1103134661-762660c8,"{'mileage': 94310, 'state_not_beaten': True, '...","{'configuration': {'id': '20058968', 'body_typ...","2.0 MT (149 л.с.), внедорожник, передний, бензин",NaN
IN_STOCK,Автомобиль приобретался у официального дилера....,"{'owners_number': 3, 'custom_cleared': True, '...","{'transport_tax': {'tax_by_year': 2235, 'year'...",used,COMMERCIAL,"['oversize', 'allowed_for_credit', 'big-trunk'...","{'hidden': False, 'is_on_moderation': False, '...",1103134468,"{'price': 735000, 'currency': 'RUR', 'EUR': 80...",{'catboost_relevance_offline': 0.0032201375846...,1103134468-a31c5df2,"{'mileage': 106591, 'state_not_beaten': True, ...","{'configuration': {'id': '7958294', 'body_type...","2.0d AT (149 л.с.), внедорожник, полный, дизель",NaN
IN_STOCK,"Продается комфортабельный, надежный внедорожни...","{'owners_number': 4, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 1325, 'year'...",used,COMMERCIAL,"['good_price', 'oversize', 'interior_panoramas...","{'hidden': False, 'is_on_moderation': False, '...",1103132985,"{'price': 499000, 'currency': 'RUR', 'EUR': 54...",{'catboost_relevance_offline': 0.0028684943138...,1103132985-156c64e0,"{'mileage': 172416, 'state_not_beaten': True, ...","{'configuration': {'id': '7147199', 'body_type...","2.0d AT (141 л.с.), внедорожник, полный, дизель",NaN
IN_STOCK,.\nУвеличенная дополнительная скидка:\n- При о...,"{'owners_number': 1, 'pts_original': True, 'cu...","{'transport_tax': {'tax_by_year': 4117, 'year'...",used,COMMERCIAL,"['oversize', 'novice-drivers', 'vin_service_hi...","{'hidden': False, 'is_on_moderation': False, '...",1103044283,"{'price': 639000, 'currency': 'RUR', 'EUR': 69...",{'catboost_relevance_offline': 0.0032411460647...,1103044283-c900e05b,"{'mileage': 92808, 'state_not_beaten': True, '...","{'configuration': {'id': '7147199', 'body_type...","2.0d MT (141 л.с.), внедорожник, полный, дизель",NaN
IN_STOCK,"Хороший, вместительный, рамный внедорожник. Му...","{'owners_number': 3, 'custom_cleared': True, '...","{'transport_tax': {'tax_by_year': 440, 'year':...",used,PRIVATE,"['oversize', 'wide-back-seats', 'big-trunk', '...","{'hidden': False, 'is_on_moderation': False, '...",1103138823,"{'price': 230000, 'currency': 'RUR', 'EUR': 25...",{'catboost_relevance_offline': 0.0031397083333...,1103138823-c07520a3,"{'mileage': 324000, 'state_not_beaten': True, ...","{'configuration': {'id': '5140431', 'body_type...","2.3d MT (80 л.с.), внедорожник, полный, дизель",NaN

In [22]:
df_t.columns

Index(['category', 'color_hex', 'delivery_info', 'description',
       'discount_options', 'documents', 'is_favorite', 'old_category_id',
       'owner_expenses', 'score', 'section', 'seller_type', 'services',
       'shark_info', 'status', 'tags', 'additional_info', 'counters',
       'grouping_info', 'hash', 'id', 'price_info', 'price_history',
       'recall_info', 'relevance', 'saleId', 'salon', 'seller',
       'service_prices', 'state', 'sub_category', 'vehicle_info', 'lk_summary',
       'multiposting', 'dealer_credit_config', 'brand_cert_info',
       'discount_price', 'badges'],
      dtype='object')

In [17]:
pd.read_csv(PATH_to_file + 'autoru-1.csv', index_col=0)

,category,color_hex,delivery_info,description,discount_options,documents,is_favorite,old_category_id,owner_expenses,score,...,service_prices,state,sub_category,vehicle_info,lk_summary,multiposting,dealer_credit_config,brand_cert_info,discount_price,badges
availability,,,,,,,,,,,,,,,,,,,,,
IN_STOCK,cars,97948F,{},ВЛАДЕЛЕЦ ОДИН! Первая запись автосалон( хотели...,{},"{'owners_number': 1, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 18675, 'year...","{'transparency': 73, 'price': 0.5, 'health': 94}",...,[],"{'mileage': 41000, 'state_not_beaten': True, '...",cars,"{'configuration': {'id': '20849260', 'body_typ...","2.0 AMT (249 л.с.), внедорожник, полный, бензин",{},NaN,NaN,NaN,NaN
IN_STOCK,cars,97948F,{},Куплен в салоне АЦ Космонавтов в октябре 2020....,{},"{'owners_number': 1, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 1410, 'year'...","{'price': 0.5, 'health': 92}",...,[],"{'damages': [{'car_part': 'FRONT_LEFT_FENDER',...",cars,"{'configuration': {'id': '20785541', 'body_typ...","1.4 AMT (150 л.с.), седан, передний, бензин",{},NaN,NaN,NaN,NaN
IN_STOCK,cars,FAFBFB,{},"Абсолютно исправный и обслуженный автомобиль,б...",{},"{'owners_number': 3, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 18375, 'year...","{'transparency': 70, 'price': 0.5, 'health': 77}",...,[],"{'mileage': 164000, 'state_not_beaten': True, ...",cars,"{'configuration': {'id': '6468932', 'body_type...","3.0d AT (245 л.с.), внедорожник, полный, дизель",{},NaN,NaN,NaN,NaN
IN_STOCK,cars,200204,{},При покупке данного автомобиля в кредит вы пол...,"{'credit': 100000, 'max_discount': 100000}","{'owners_number': 1, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 16875, 'year...",{},...,[],"{'mileage': 99000, 'state_not_beaten': True, '...",cars,"{'configuration': {'id': '8351305', 'body_type...","2.0 AT (225 л.с.), внедорожник, полный, бензин",{},"{'credit_term_values': [1, 2, 3, 4, 5, 6, 7], ...",NaN,NaN,NaN
IN_STOCK,cars,040001,{},"Все автомобили, представленные в продаже, прох...","{'tradein': 40000, 'credit': 80000, 'max_disco...","{'owners_number': 4, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 9500, 'year'...",{},...,[],"{'mileage': 77000, 'state_not_beaten': True, '...",cars,"{'configuration': {'id': '20246013', 'body_typ...","1.8 AMT (190 л.с.), седан, передний, бензин",{},"{'credit_term_values': [1, 2, 3, 4, 5, 6, 7], ...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IN_STOCK,cars,0000CC,{},Реальный пробег. Без окрасов.\nБолее 150 автом...,"{'tradein': 25000, 'credit': 25000, 'max_disco...","{'owners_number': 2, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 5215, 'year'...",{},...,[],"{'mileage': 94310, 'state_not_beaten': True, '...",cars,"{'configuration': {'id': '20058968', 'body_typ...","2.0 MT (149 л.с.), внедорожник, передний, бензин",{},NaN,NaN,NaN,NaN
IN_STOCK,cars,040001,{},Автомобиль приобретался у официального дилера....,{},"{'owners_number': 3, 'custom_cleared': True, '...",False,15,"{'transport_tax': {'tax_by_year': 2235, 'year'...",{},...,[],"{'mileage': 106591, 'state_not_beaten': True, ...",cars,"{'configuration': {'id': '7958294', 'body_type...","2.0d AT (149 л.с.), внедорожник, полный, дизель",{},NaN,NaN,NaN,NaN
IN_STOCK,cars,FAFBFB,{},"Продается комфортабельный, надежный внедорожни...",{},"{'owners_number': 4, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 1325, 'year'...",{},...,[],"{'mileage': 172416, 'state_not_beaten': True, ...",cars,"{'configuration': {'id': '7147199', 'body_type...","2.0d AT (141 л.с.), внедорожник, полный, дизель",{},"{'credit_term_values': [1, 2, 3, 4, 5], 'credi...",NaN,NaN,NaN
IN_STOCK,cars,CACECB,{},.\nУвеличенная дополнительная скидка:\n- При о...,{},"{'owners_number': 1, 'pts_original': True, 'cu...",False,15,"{'transport_tax': {'tax_by_year': 4117, 'year'...",{},...,[],"{'mileage': 92808, 'state_not_beaten': True, '...",cars,"{'configuration': {'id': '7147199', 'body_type...","2.0d MT (141 л.с.), внедорожник, полный, дизель",{},NaN,NaN,NaN,NaN
IN_STOCK,cars,0000CC,{},"Хороший, вместительный, рамный внедорожник. Му...",{},"{'owners_number': 3, 'custom_cleared': True, '...",False,15,"{'transport_tax': {'tax_by_year': 440, 'year':...","{'transparency': 70, 'price': 0.5}",...,[],"{'mileage': 324000, 'state_not_beaten': True, ...",cars,"{'configuration': {'id': '5140431', 'body_type...","2.3d MT (80 л.с.), внедорожник, полный, дизель",{},NaN,NaN,NaN,NaN

### 2. Импорт данных о марках и моделях

In [2]:
df_marks_and_models = pd.read_csv(PATH_to_file + 'all_car_brands_and_their_models_from_auto_ru.csv', index_col=0)
print('Кол-во марок: ', df_marks_and_models.shape[0])
display(df_marks_and_models.head(2))

Кол-во марок:  262

                                                  Models
Mark
AC                   ['378_GT', 'ACE', 'ACECA', 'COBRA']
ACURA  ['CL', 'CSX', 'EL', 'ILX', 'INTEGRA', 'LEGEND'...

### 2. Отбор марок для парсинга

In [3]:
# кол-во объявлений на сайте на 9.9.2020 
dict_of_num_cars_of_models ={'AC':2, 'Acura':94, 'Alfa Romeo':65, 'Alpina':10, 
                             'AMC':2, 'Ariel':1, 'Asia':1, 'Aston Martin':25, 
                             'Audi':4093, 'Austin Healey':1, 'Bajaj':3, 
                             'Bentley':104, 'BMW':7423, 'Borgward':1, 
                             'Brilliance':10, 'Buick':17, 'BYD':22, 
                             'Cadillac':321, 'Changan':100, 'Chery':593, 
                             'Chevrolet':3670, 'Chrysler':316, 'Citroen':1142, 
                             'Dacia':9, 'Daewoo':1024, 'Daihatsu':47, 
                             'Daimler':5, 'Datsun':212, 'Delage':1, 'Derways':2, 
                             'DKW':1, 'Dodge':413, 'DongFeng':25, 'Doninvest':2, 
                             'DS':3, 'DW Hower':8, 'Eagle':1, 'Excalibur':1, 
                             'FAW':66, 'Ferrari':29, 'Fiat':206, 'Ford':4812, 
                             'Foton':2, 'GAC':14, 'Geely':302, 'Genesis':54, 
                             'GMC':26, 'Great Wall':420, 'Hafei':6, 'Haima':12, 
                             'Haval':110, 'Hawtai':4, 'Heinkel':1, 'Honda':1179, 
                             'HuangHai':1, 'Hummer':70, 'Hyundai':5712, 
                             'Infiniti':1041, 'Innocenti':1, 'Iran Khodro':21, 
                             'Isuzu':43, 'JAC':8, 'Jaguar':308, 'Jeep':466, 'JMC':1, 
                             'Kia':5595, 'LADA (ВАЗ)':8935, 'Lamborghini':14, 
                             'Lancia':8, 'Land Rover':1616, 'Lexus':985, 
                             'Lifan':295, 'Lincoln':62, 'Lotus':1, 'Luxgen':9, 
                             'Mahindra':1, 'Maserati':54, 'Maybach':7, 
                             'Mazda':2311, 'McLaren':5, 'Mercedes-Benz':8005, 
                             'Mercury':16, 'Metrocab':2, 'MG':10, 'MINI':313, 
                             'Mitsubishi':3935, 'Mitsuoka':3, 'Nissan':5776, 
                             'Oldsmobile':10, 'Opel':3131, 'Packard':2, 
                             'Peugeot':1636, 'Plymouth':13, 'Pontiac':38, 
                             'Porsche':714, 'Proton':3, 'PUCH':1, 'Ravon':112, 
                             'Renault':2771, 'Rolls-Royce':55, 'Rover':69, 
                             'Saab':147, 'Saturn':9, 'Scion':9, 'SEAT':77, 
                             'Shanghai Maple':1, 'Skoda':2810, 'Smart':89, 
                             'SsangYong':718, 'Subaru':934, 'Suzuki':878, 
                             'Tatra':5, 'Tesla':43, 'Tianma':2, 'Toyota':4648, 
                             'Triumph':1, 'Vauxhall':1, 'Volkswagen':7109, 
                             'Volvo':2069, 'Vortex':91, 'Wartburg':1, 'Willys':2, 
                             'Zotye':15, 'ZX':4, 'ГАЗ':935, 'Гоночный болид':2, 
                             'ЗАЗ':231, 'ЗИЛ':2, 'ИЖ':129, 'ЛуАЗ':45, 
                             'Москвич':198, 'СМЗ':4, 'ТагАЗ':68, 'УАЗ':1107}

In [4]:
models_dict = {'AC':3,'AMC':4,'AURUS':10,'Acura':145,'Adler':4,'Alfa Romeo':145,'Alpina':10,'Ariel':1,'Aro':7,'Asia':7,'Aston Martin':20,'Auburn':1,'Audi':11130,'Austin':2,'BAIC':2,'BMW':16647,'BYD':125,'Bentley':173,'Borgward':1,'Brabus':2,'Brilliance':94,'Bugatti':1,'Buick':44,'CHERYEXEED':78,'Cadillac':692,'Chana':1,'ChangFeng':3,'Changan':484,'Changhe':2,'Chery':3429,'Chevrolet':12926,'Chrysler':650,'Citroen':2421,'DKW':1,'DS':5,'DW Hower':18,'Dacia':43,'Dadi':5,'Daewoo':4992,'Daihatsu':373,'Daimler':1,'Datsun':1219,'Delage':1,'Derways':14,'Dodge':771,'DongFeng':51,'Doninvest':23,'Eagle':3,'FAW':277,'FSO':2,'Ferrari':29,'Fiat':909,'Fisker':1,'Ford':12124,'Foton':10,'GAC':10,'GMC':45,'Geely':2060,'Genesis':83,'Geo':8,'Great Wall':900,'Hafei':47,'Haima':99,'Hanomag':1,'Haval':1339,'Hawtai':10,'Heinkel':1,'Honda':5698,'HuangHai':2,'Hudson':1,'Hummer':162,'Hyundai':23231,'Infiniti':1935,'Iran Khodro':79,'Isuzu':149,'JAC':80,'Jaguar':717,'Jeep':937,'Jinbei':7,'Kia':20809,'LADA (ВАЗ)':77398,'LTI':1,'Lamborghini':16,'Lancia':33,'Land Rover':3476,'Landwind':3,'Lexus':3932,'Lifan':2209,'Ligier':1,'Lincoln':186,'Luxgen':23,'MG':19,'MINI':1042,'Mahindra':4,'Marussia':1,'Maruti':1,'Maserati':97,'Maybach':11,'Mazda':8327,'McLaren':3,'Mercedes-Benz':21671,'Mercury':37,'Metrocab':1,'Mitsubishi':11276,'Mitsuoka':4,'Nissan':19415,'Oldsmobile':16,'Opel':9582,'PUCH':7,'Packard':1,'Peugeot':4462,'Plymouth':21,'Pontiac':113,'Porsche':1590,'Proton':12,'RAM':32,'Ravon':291,'Renault':19025,'Renault Samsung':2,'Rolls-Royce':57,'Rover':222,'SEAT':214,'Saab':271,'Saturn':33,'Scion':19,'Shanghai Maple':8,'ShuangHuan':2,'Simca':1,'Skoda':9601,'Smart':165,'SsangYong':1840,'Subaru':2436,'Suzuki':2940,'TATA':4,'Talbot':1,'Tatra':4,'Tesla':152,'Tianma':2,'Tianye':10,'Toyota':24191,'Trabant':4,'Triumph':3,'Vauxhall':1,'Volkswagen':19792,'Volvo':3346,'Vortex':395,'Wanderer':5,'Wartburg':3,'Willys':13,'Xin Kai':3,'Yulon':1,'ZX':15,'Zibar':1,'Zotye':85,'Автокам':1,'ГАЗ':4318,'Гоночный автомобиль':6,'ЗАЗ':1380,'ЗИЛ':7,'ЗиС':3,'ИЖ':626,'Канонир':1,'ЛуАЗ':299,'Москвич':671,'СМЗ':21,'ТагАЗ':189,'УАЗ':5713}

In [5]:
# уберем модели с кол-вом объявлений ниже 300 и повысим регистр индексов 
list_keys_to_delete = []
for mark in models_dict.keys():
    if models_dict[mark] < 300:
        list_keys_to_delete.append(mark)
    
for key in list_keys_to_delete: del models_dict[key]

for mark in list(models_dict.keys()):
    mark_up = mark.upper()
    models_dict[mark_up]=models_dict.pop(mark)

In [6]:
# посмотрим на список получившихся моделей
print(*models_dict, sep=',')

AUDI,BMW,CADILLAC,CHANGAN,CHERY,CHEVROLET,CHRYSLER,CITROEN,DAEWOO,DAIHATSU,DATSUN,DODGE,FIAT,FORD,GEELY,GREAT WALL,HAVAL,HONDA,HYUNDAI,INFINITI,JAGUAR,JEEP,KIA,LADA (ВАЗ),LAND ROVER,LEXUS,LIFAN,MINI,MAZDA,MERCEDES-BENZ,MITSUBISHI,NISSAN,OPEL,PEUGEOT,PORSCHE,RENAULT,SKODA,SSANGYONG,SUBARU,SUZUKI,TOYOTA,VOLKSWAGEN,VOLVO,VORTEX,ГАЗ,ЗАЗ,ИЖ,МОСКВИЧ,УАЗ

In [7]:
# Удалим отечественные модели
for key in ['LADA (ВАЗ)','ГАЗ','УАЗ', 'ЗАЗ', 'ИЖ', 'МОСКВИЧ']: del models_dict[key]

In [8]:
# проверим что названия моделей совпадают с названиями каталога сайта auto.Ru
list_marks_df = list(df_marks_and_models.index)
list_marks_to_check = []
for mark in models_dict.keys():
    if mark not in list_marks_df:
        list_marks_to_check.append(mark)
print(f'всего марок с кол-вом объявлений более 300:= {len(dict_of_num_cars_of_models)}')
print('список марок, которые нужно проверить :=', *list_marks_to_check)

всего марок с кол-вом объявлений более 300:= 134
список марок, которые нужно проверить := GREAT WALL LAND ROVER MERCEDES-BENZ SSANGYONG

In [9]:
# эта строка позволяет проверить значение с пробелом или с дефисом для корректировки
models_dict['GREAT WALL']

900

In [10]:
# исправим несоответствия
models_dict['GREAT_WALL']=models_dict.pop('GREAT WALL')
models_dict['LAND_ROVER']=models_dict.pop('LAND ROVER')
models_dict['MERCEDES']=models_dict.pop('MERCEDES-BENZ')
models_dict['SSANG_YONG']=models_dict.pop('SSANGYONG')

In [11]:
# еще раз проверим что названия моделей совпадаю с названиями каталога сайта auto.Ru
list_marks_df = list(df_marks_and_models.index)
list_marks_to_check = []
for mark in models_dict.keys():
    if mark not in list_marks_df:
        list_marks_to_check.append(mark)
print(f'всего марок с кол-вом объявлений более 300 := {len(models_dict)}')
print('список марок, которые нужно проверить :=', *list_marks_to_check)

всего марок с кол-вом объявлений более 300 := 43
список марок, которые нужно проверить :=

In [12]:
# запишем список релевантных марок для парсинга
list_of_relevant_marks = list(models_dict.keys())

In [13]:
sum_of_ads = sum(models_dict.values())
print(f"примерное кол-во строк после парсинга должно быть := {sum_of_ads}")

примерное кол-во строк после парсинга должно быть := 296941

In [14]:
models_dict

{'AUDI': 11130,
 'BMW': 16647,
 'CADILLAC': 692,
 'CHANGAN': 484,
 'CHERY': 3429,
 'CHEVROLET': 12926,
 'CHRYSLER': 650,
 'CITROEN': 2421,
 'DAEWOO': 4992,
 'DAIHATSU': 373,
 'DATSUN': 1219,
 'DODGE': 771,
 'FIAT': 909,
 'FORD': 12124,
 'GEELY': 2060,
 'HAVAL': 1339,
 'HONDA': 5698,
 'HYUNDAI': 23231,
 'INFINITI': 1935,
 'JAGUAR': 717,
 'JEEP': 937,
 'KIA': 20809,
 'LEXUS': 3932,
 'LIFAN': 2209,
 'MINI': 1042,
 'MAZDA': 8327,
 'MITSUBISHI': 11276,
 'NISSAN': 19415,
 'OPEL': 9582,
 'PEUGEOT': 4462,
 'PORSCHE': 1590,
 'RENAULT': 19025,
 'SKODA': 9601,
 'SUBARU': 2436,
 'SUZUKI': 2940,
 'TOYOTA': 24191,
 'VOLKSWAGEN': 19792,
 'VOLVO': 3346,
 'VORTEX': 395,
 'GREAT_WALL': 900,
 'LAND_ROVER': 3476,
 'MERCEDES': 21671,
 'SSANG_YONG': 1840}

### 3. Подготовка к парсингу

In [68]:
HEADERS = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3',
    'Connection': 'keep-alive',
    'Content-Length':'103',
    'content-type':'application/json',
    'Cookie':'_csrf_token=0b9bfe638dd0b95a7c3ac9b3fd59d540eae8102094150176; autoru_sid=a%3Ag60697fdd20d5osjl7hjk5o65qso5f3m.bbec9e47fe6c357861dac8894dd324be%7C1617526749509.604800.Rmi4CAt4gY8VoAVCNf8yGA.WhKyb55vGRLnuhVwmAYw-WpbpGJhnU11ZIgNnQ0xwlQ; autoruuid=g60697fdd20d5osjl7hjk5o65qso5f3m.bbec9e47fe6c357861dac8894dd324be; autoru_gdpr=1; suid=8b392ef0642f31eba6e490553b2a8876.aa730c703f9c9a4f5e66993fe8c916ea; from_lifetime=1617559952775; from=direct; yuidlt=1; yandexuid=8768961311617526753; crookie=1qrlqxZ2MieUUgilutZaKTa…Ee2fHj8lmdQBvzx9tU0pT1dAsLGQFeMvntjuCGj+h22jxmOfWIg=; cmtchd=MTYxNzUyNjc2MDU5Ng==; gdpr=0; cycada=p92JQFOQLJpa73XwSOM/xy61EE8dGReKfzAjoY3mt3A=; _ym_uid=1617526759299819712; _ym_d=1617559952; _ym_isad=2; mindboxDeviceUUID=ab564749-0f98-40b1-89d2-41b766a1c42d; directCrm-session=%7B%22deviceGuid%22%3A%22ab564749-0f98-40b1-89d2-41b766a1c42d%22%7D; _ga=GA1.2.1029486733.1617532156; _gid=GA1.2.1469364259.1617532156; tmr_reqNum=3; tmr_lvid=bf1506bfca36781b64ee3b80ce17ae53; tmr_lvidTS=1617532156060; X-Vertis-DC=vla',
    'Host': 'auto.ru',
    'Origin':'https://auto.ru',
    'Referer':'https://auto.ru/',
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0',
    'x-client-app-version':'5f535b6dbd',
    'x-client-date':'1617559954352',
    'x-csrf-token':'0b9bfe638dd0b95a7c3ac9b3fd59d540eae8102094150176',
    'x-page-request-id':'52e324b5b6813d1a9c9635b956cb5b85',
    'x-requested-with':'fetch'
}

In [69]:
url = "https://auto.ru/-/ajax/desktop/listing/"

In [71]:
# посмотрим какие столбцы нам нужны 
test = pd.read_csv('data/test.csv')
print('Кол-во столбцов теста:', test.shape[1])
print('Названия столбцов теста:', list(test.columns))

# вывод всех столбцов датафрейма
pd.set_option('display.max_columns', None)
test.head(2)

Кол-во столбцов теста: 32
Названия столбцов теста: ['bodyType', 'brand', 'car_url', 'color', 'complectation_dict', 'description', 'engineDisplacement', 'enginePower', 'equipment_dict', 'fuelType', 'image', 'mileage', 'modelDate', 'model_info', 'model_name', 'name', 'numberOfDoors', 'parsing_unixtime', 'priceCurrency', 'productionDate', 'sell_id', 'super_gen', 'vehicleConfiguration', 'vehicleTransmission', 'vendor', 'Владельцы', 'Владение', 'ПТС', 'Привод', 'Руль', 'Состояние', 'Таможня']

,bodyType,brand,car_url,color,complectation_dict,description,engineDisplacement,enginePower,equipment_dict,fuelType,image,mileage,modelDate,model_info,model_name,name,numberOfDoors,parsing_unixtime,priceCurrency,productionDate,sell_id,super_gen,vehicleConfiguration,vehicleTransmission,vendor,Владельцы,Владение,ПТС,Привод,Руль,Состояние,Таможня
0,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,синий,NaN,"Все автомобили, представленные в продаже, прох...",1.2 LTR,105 N12,"{""engine-proof"":true,""tinted-glass"":true,""airb...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,74000,2013,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.2 AMT (105 л.с.),5,1603226273,RUB,2014,1100575026,"{""id"":""10373605"",""displacement"":1197,""engine_t...",LIFTBACK ROBOT 1.2,роботизированная,EUROPEAN,3 или более,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен
1,лифтбек,SKODA,https://auto.ru/cars/used/sale/skoda/octavia/1...,чёрный,NaN,ЛОТ: 01217195\nАвтопрага Север\nДанный автомоб...,1.6 LTR,110 N12,"{""cruise-control"":true,""asr"":true,""esp"":true,""...",бензин,https://autoru.naydex.net/o9DBXQ270/5ac010hAY0...,60563,2017,"{""code"":""OCTAVIA"",""name"":""Octavia"",""ru_name"":""...",OCTAVIA,1.6 MT (110 л.с.),5,1603226277,RUB,2017,1100549428,"{""id"":""20913311"",""displacement"":1598,""engine_t...",LIFTBACK MECHANICAL 1.6,механическая,EUROPEAN,1 владелец,NaN,Оригинал,передний,Левый,Не требует ремонта,Растаможен

In [88]:
# сделаем тестовый вызов запроса для BMW модели M6 и выведем его на экран, чтобы по нему можно было сделать функцию для создания 23 необходимых столбцов


# но сначала установим главные параметры запроса
mark = 'BMW'  # марка
model = 'M6'  # модель
geo_radius = 200  # радиус вокруг москвы = 200 км
geo_id = [213]  # Москва
top_days = "1"  # кол-во дней от текущей даты назад за которые запрашиваем объявления 

param = {
                'catalog_filter' : [{"mark": mark, "model": model}],
                'section': "all",
                'category': "cars",
                'sort': "fresh_relevance_1-desc",
                "top_days":top_days,
                "geo_radius":geo_radius,
                "geo_id":geo_id,
                'page': 1
            }

response = requests.post(url, json=param, headers = HEADERS)
data = response.json()
for elem in data['offers']:
    print(elem)
    break

ConnectionError: HTTPSConnectionPool(host='auto.ru', port=443): Max retries exceeded with url: /-/ajax/desktop/listing/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B32D1F3A00>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

In [84]:
try:
    response = requests.post(url, json=param, headers = HEADERS)    
except UnicodeEncodeError:
        pass

Так как парсинг с kaggle оказался не возможным из-за блокировки исходящих кукис, то я выложил сюда скриншоты выполнения строк выше чтобы вы могли съоринтироваться
<img src="https://i0.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_1.png" width="1000px"/>

<img src="https://ia.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_2.png"  width="1000px"/>

In [79]:
# строка для проверки содержания элемента запроса
elem['additional_info']['hidden']

NameError: name 'elem' is not defined

In [ ]:
def utils_clean_values_dict(d_dict):
    for elem in d_dict:
        d_dict[elem] = 0
    return

In [ ]:
# создаем вспомагательный словарь, в который будем записывать необходимые данные из каждого объявления
dict_columns = {'bodyType':0, 'brand':0, 'color':0, 'fuelType':0, 'modelDate':0, 
                'name':0, 'numberOfDoors':0, 'productionDate':0, 
                'vehicleConfiguration':0, 'vehicleTransmission':0, 
                'engineDisplacement':0, 'enginePower':0, 'description':0, 
                'mileage':0, 'Комплектация':0, 'Привод':0, 'Руль':0, 
                'Состояние':0, 'Владельцы':0, 'ПТС':0, 'Таможня':0, 
                'Владение':0, 'price':0}

# создаем функцию для обработки 23 необходимых столбцов из объявления в словарь
def from_elem_to_dict(d_elem, d_dict):
    utils_clean_values_dict(d_dict)
    
    try: d_dict['bodyType'] = d_elem['vehicle_info']['configuration']['human_name']
    except: d_dict['bodyType'] = None

    try: d_dict['brand'] = d_elem['vehicle_info']['mark_info']['code']
    except: d_dict['brand'] = None

    try: d_dict['color'] = d_elem['color_hex']
    except: d_dict['color'] = None

    try: d_dict['fuelType'] = d_elem['lk_summary'].split()[-1]
    except: d_dict['fuelType'] = None

    try: d_dict['modelDate'] = d_elem['vehicle_info']['super_gen']['year_from']
    except: d_dict['modelDate'] = None

    try: d_dict['name'] =  d_elem['vehicle_info']['tech_param']['human_name']
    except: d_dict['name'] = None

    try: d_dict['numberOfDoors'] = d_elem['vehicle_info']['configuration']['doors_count']
    except: d_dict['numberOfDoors'] = None

    try: d_dict['productionDate'] = d_elem['documents']['year']
    except: d_dict['productionDate'] = None

    try: d_dict['vehicleTransmission'] = d_elem['vehicle_info']['tech_param']['transmission']
    except: d_dict['vehicleTransmission'] = None

    try: d_dict['engineDisplacement'] = d_elem['vehicle_info']['tech_param']['human_name'].split()[0]
    except: d_dict['engineDisplacement'] = None

    try: d_dict['vehicleConfiguration'] = elem['vehicle_info']['configuration']['body_type']+' '+d_dict['vehicleTransmission']+' '+d_dict['engineDisplacement']
    except: d_dict['vehicleConfiguration'] = None

    try: d_dict['enginePower'] = d_elem['vehicle_info']['tech_param']['power']
    except: d_dict['enginePower'] = None

    try: d_dict['description'] = d_elem['description']
    except: d_dict['description'] = None

    try: d_dict['mileage'] = d_elem['state']['mileage']
    except: d_dict['mileage'] = None

    try: d_dict['Комплектация'] = d_elem['vehicle_info']['complectation']
    except: d_dict['Комплектация'] = None

    try: d_dict['Привод'] = d_elem['lk_summary'].split(', ')[-2]
    except: d_dict['Привод'] = None

    try: d_dict['Руль'] = d_elem['vehicle_info']['steering_wheel']
    except: d_dict['Руль'] = None

    # 'Состояние' не найдено
    d_dict['Состояние'] = None

    try: d_dict['Владельцы'] = d_elem['documents']['owners_number']
    except: d_dict['Владельцы'] = None

    try: d_dict['ПТС'] = d_elem['documents']['pts']
    except: d_dict['ПТС'] = None

    try: d_dict['Таможня'] = d_elem['documents']['custom_cleared']
    except: d_dict['Таможня'] = None

    try: d_dict['Владение'] =  d_elem['documents']['purchase_date']
    except: d_dict['Владение'] = None


    try: d_dict['price'] = d_elem['price_info']['RUR']
    except: d_dict['price'] = None

    # дата размещения объявления решил добавить 
    try: d_dict['start_date'] =  d_elem['additional_info']['hot_info']['start_time']
    except: d_dict['start_date'] = None

    # статус объявления 
    try: d_dict['hidden'] =  d_elemelem['additional_info']['hidden']
    except: d_dict['hidden'] = None

    # модель 
    d_dict['model'] =  model

    return

# тест функции 
from_elem_to_dict(elem, dict_columns)

In [ ]:
# проверяем формат тестового запроса с сайта и теста с кагл
display(pd.DataFrame(dict_columns).head(2))
test[test['enginePower']=='560 N12'].head(2)

<img src="https://ia.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_3.png" width="1000px"/>

### 4. Парсинг

In [ ]:
auto_ru = {}

iter_of_ads, iter_of_marks, old_iter_of_ads, sum_ads, sum_ads_from_dict = 0,0,0,0,0
space = ' '
start_time_global = time.clock()

for mark in list_of_relevant_marks:
    start_time = time.clock()
    list_of_models = json.loads(df_marks_and_models.loc[mark, 'Models'].replace("'", '"'))
    for model in list_of_models:
        for num_page in range(1, 200):
            param = {
                'catalog_filter' : [{"mark": mark, "model": model}],
                'section': "all",
                'category': "cars",
                'sort': "fresh_relevance_1-desc",
                "top_days":"900",
                "geo_radius":200,
                "geo_id":[213],
                'page': num_page
            }
            response = requests.post(url, json=param, headers = HEADERS)
            data = response.json()

            if data['offers'] != []:
                for elem in data['offers']:
                    from_elem_to_dict(elem, dict_columns)
                    auto_ru[iter_of_ads] = dict_columns.copy()
                    iter_of_ads += 1
            else:
                break
    iter_of_marks +=1
    temp_1 = iter_of_ads-old_iter_of_ads
    temp_2 = dict_of_num_cars_of_models[mark]
    temp_3 = temp_1/temp_2
    temp_4 = space*abs(13-len(mark)-len(str(iter_of_marks)))
    temp_5 = int(time.clock() - start_time)
    temp_8 = round(temp_3*100,2)
    temp_7 = space*abs(18-len(str(temp_1))-len(str(temp_2))-len(str(temp_8))-len(str(temp_5)))
    temp_9 = int(time.clock() - start_time_global)
    

    sum_ads += temp_1
    sum_ads_from_dict += temp_2
    temp_def = sum_ads/sum_ads_from_dict
    temp_6 = (sum_of_ads*temp_def - iter_of_ads)*temp_9/sum_ads


    print (f'{iter_of_marks}.{mark} {temp_4} ушло:{temp_5} сек., стр. {temp_1} из {temp_2} {temp_8}%,{temp_7}всего стр. {iter_of_ads}, прогноз {int(temp_6/60)} мин.')

    old_iter_of_ads=iter_of_ads

print (f'Всего спарсили := {iter_of_ads} строк, на это ушло: {int((time.clock() - start_time_global)/60)} мин., ')

<img src="https://ia.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_4.png"  width="1000px"/>

<img src="https://i0.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_5.png" width="1000px"/>

In [ ]:
# запись датасета
df_auto_ru = pd.DataFrame(auto_ru).T
df_auto_ru.to_csv(PATH_to_file+'all_auto_ru_09_09_2020.csv', index=False)
print(f'кол-во строк датасета:= {len(df_auto_ru)}')

In [ ]:
# визуальный контроль
df_auto_ru.head(3)

<img src="https://i0.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_6.png" width="1000px"/>

<img src="https://ia.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_7.png"  width="1000px"/>

<img src="https://i0.wampi.ru/2020/09/18/p1_parsing_dst10_rds6_pic_8.png" width="300px">

**Резюме:**  
- Первоначальный парсинг показал, что на сайте много старых объявлений . Так как изначально за последние 90 дней мы получили 43% от всех объявлений по BMW, поэтому пришлось скачать за последние 900 дней, чтобы получить полные цифры заявленные на сайте. 
- Чтобы протестировать код ноутбука лучше всего скачать его на локальную машину. Не заывайте скачивать датасет всех марок и моделей для сайта. Удачного парсинга!

Если ноутбук вам понравился прошу оценить стрелкой вверх. Также вы можете оценить датасеты всех моделей и марок для сайта https://www.kaggle.com/sokolovaleks/all-brands-and-models-for-auto-ru-09-09-2020, а также датасет всех объявлений сайта на 9.9.2020 https://www.kaggle.com/sokolovaleks/parsing-all-moscow-auto-ru-09-09-2020.

Оригинал ноутбука вы всегда можете найти на гитхабе в папке проекта - https://github.com/dst10rds6/rds6/tree/master/parsing

**Спасибо за внимание**
Если остались вопросы и/или замечания - пишите